package interviewQuestions;

import java.io.*;

/**
 * ============================================================================
 * INTERVIEW QUESTIONS PART 7: Exceptions & Input/Output (IO)
 * ============================================================================
 * This file contains 30 highly detailed Java interview questions.
 * Each question provides a deep-dive English explanation covering the 'What', 
 * 'Why', and 'How', along with practical Java code snippets.
 * ============================================================================
 */
public class Part7_ExceptionsAndIO {

    public static void main(String[] args) {
        System.out.println("Running Part 7: Exceptions and IO...");
    }

    /**
     * Q1: [Medium] Describe the overall Throwable Hierarchy in Java.
     * 
     * DETAILED EXPLANATION:
     * The `java.lang.Throwable` class is the absolute supreme root of the entire exception hierarchy. 
     * Nothing can be thrown using the `throw` keyword unless it inherits from Throwable. 
     * It splits into two main branches:
     * 1. Error: Represents critical, fatal system malfunctions (like OutOfMemoryError).
     * 2. Exception: Represents logical or environmental errors that a developer can actually recover from. 
     *    The Exception branch further splits into "Checked" exceptions and "Unchecked" (Runtime) exceptions.
     */
    public void throwableHierarchy() {
        System.out.println("Throwable splits into -> Errors (Fatal) and Exceptions (Recoverable).");
    }

    /**
     * Q2: [Easy] What is the exact difference between an Error and an Exception?
     * 
     * DETAILED EXPLANATION:
     * Errors (like StackOverflowError) are generated by the JVM environment itself. They indicate that the 
     * physical system is compromised and the application cannot realistically continue. You should NEVER write 
     * a try-catch block to catch an Error.
     * Exceptions (like NullPointerException or FileNotFoundException) are generated by the application code or 
     * user interactions. They indicate a fault that the program can gracefully handle, warn the user about, 
     * and continue running.
     */
    public void errorVsException() {
        System.out.println("Exceptions are handled by code. Errors terminate the JVM process.");
    }

    /**
     * Q3: [Medium] Deeply explain Checked Exceptions.
     * 
     * DETAILED EXPLANATION:
     * Checked Exceptions are exceptions that the Java Compiler explicitly CHECKS for before allowing the program 
     * to compile. They do not inherit from RuntimeException. 
     * They typically represent scenarios entirely outside the control of the program (e.g., attempting to read a 
     * file that a user deleted from their hard drive: IOException). 
     * The compiler FORCES the developer to acknowledge this risk. You must either wrap the risky code in a 
     * `try-catch` block, or append a `throws` declaration to the method signature to pass the responsibility 
     * up to the caller.
     */
    public void checkedExceptions() {
        System.out.println("Checked Exceptions: Validated at compile-time. Forces developer intervention.");
    }

    /**
     * Q4: [Easy] Deeply explain Unchecked Exceptions.
     * 
     * DETAILED EXPLANATION:
     * Unchecked Exceptions (which all inherit from `RuntimeException`) are NOT checked by the compiler. 
     * They almost exclusively represent logical bugs or bad programming practices (e.g., dividing by zero, 
     * trying to access the 100th element of a 5-element array). 
     * Because they signify code flaws that should be fixed rather than "expected environmental conditions", 
     * the compiler does not force you to write try-catch blocks for them.
     */
    public void uncheckedExceptions() {
        System.out.println("Unchecked Exceptions: Runtime logic flaws that evade compile-time checking.");
    }

    /**
     * Q5: [Easy] Detail the mechanics of the try-catch Block.
     * 
     * DETAILED EXPLANATION:
     * A protective structure. The `try` block acts as an isolation chamber. You put dangerous, exception-prone 
     * code inside it. If an exception detonates, the JVM instantly halts execution of the try block and throws 
     * an Exception Object.
     * The JVM then looks for a corresponding `catch` block that matches the type of the Exception Object. 
     * If found, the catch block absorbs the crash, executes its recovery code, and allows the rest of the 
     * program outside the try-catch structure to continue running normally.
     */
    public void tryCatchBlock() {
        System.out.println("Try-Catch: Isolates dangerous code and gracefully handles detonations.");
    }

    /**
     * Q6: [Medium] What are the strict rules for Multiple catch Blocks?
     * 
     * DETAILED EXPLANATION:
     * You can attach multiple `catch` blocks to a single `try` block to handle different crises uniquely. 
     * THE GOLDEN RULE: You must always order the catch blocks from the MOST specific subclass exception at the top, 
     * down to the MOST generic superclass exception at the bottom. 
     * If you put `catch (Exception e)` at the very top, it acts as a massive net that catches absolutely everything. 
     * Any specific catch blocks below it (like `catch (IOException e)`) would become completely unreachable, and 
     * the compiler will throw an error.
     */
    public void multipleCatchBlocks() {
        System.out.println("Multiple Catch: Must be ordered from Specific Subclasses to General Superclasses.");
    }

    /**
     * Q7: [Medium] What is the true power of the finally Block?
     * 
     * DETAILED EXPLANATION:
     * The `finally` block is attached to the end of a try-catch structure. Its code is GUARANTEED to execute, 
     * no matter what happens. 
     * - If the try block succeeds: finally runs.
     * - If the try block crashes and is caught: finally runs.
     * - If the try block crashes and is NOT caught: finally runs right before the JVM terminates the thread.
     * - Even if there is a `return` statement inside the try block, the JVM pauses, runs the finally block, 
     *   and THEN returns the value.
     * It is used exclusively to close connections, file streams, and release locks so system resources aren't leaked.
     * (The ONLY way to stop it is by calling `System.exit(0)`).
     */
    public void finallyBlock() {
        System.out.println("Finally: Unstoppable code execution used for critical resource cleanup.");
    }

    /**
     * Q8: [Easy] Explain the 'throw' Keyword.
     * 
     * DETAILED EXPLANATION:
     * The `throw` keyword is an action verb. It is used explicitly by a developer inside a method to physically 
     * create an exception and launch it. 
     * You instantiate the Exception object (e.g., `new IllegalArgumentException("Age too low")`) and use `throw` 
     * to immediately halt the method and push the error object out to the JVM.
     */
    public void throwKeyword() {
        System.out.println("Throw: Physically instantiates and detonates an Exception object.");
    }

    /**
     * Q9: [Easy] Explain the 'throws' Keyword.
     * 
     * DETAILED EXPLANATION:
     * The `throws` keyword is a warning sign. It is attached strictly to the end of a Method Signature. 
     * It serves as a declaration to the Java Compiler and to any other developer calling the method: "Warning! 
     * This method might generate a Checked Exception. I am not handling it here. If you call my method, YOU 
     * are legally required to put it in a try-catch block."
     */
    public void throwsKeyword() {
        System.out.println("Throws: A method signature declaration that passes responsibility to the caller.");
    }

    /**
     * Q10: [Medium] How and why do you build Custom Exceptions?
     * 
     * DETAILED EXPLANATION:
     * Java's built-in exceptions (like IOException) are great for technical issues, but terrible for business logic. 
     * If a user tries to withdraw more money than they have, throwing a generic `Exception` is unclear. 
     * You create a Custom Exception by creating a class like `InsufficientFundsException` that `extends RuntimeException`. 
     * You provide a constructor that takes a String message and passes it to `super(message)`. This makes logs 
     * highly readable and domain-specific.
     */
    public void customExceptions() {
        System.out.println("Custom Exceptions: Business-domain specific error classes extending RuntimeException.");
    }

    /**
     * Q11: [Medium] How does Try-With-Resources revolutionize code?
     * 
     * DETAILED EXPLANATION:
     * Introduced in Java 7, Try-With-Resources completely eliminates the need for messy, ugly `finally` blocks 
     * filled with `stream.close()` calls. 
     * You declare your file streams or database connections inside parenthesis directly next to the `try` keyword. 
     * The JVM takes full responsibility for monitoring those resources. The millisecond the try block finishes 
     * (or crashes), the JVM automatically and safely closes every single resource you opened, preventing memory leaks.
     */
    public void tryWithResources() {
        System.out.println("Try-With-Resources: Automates the closing of resources, eliminating finally blocks.");
    }

    /**
     * Q12: [Medium] What is the AutoCloseable Interface?
     * 
     * DETAILED EXPLANATION:
     * Try-With-Resources is basically magic, but it has one strict rule: it can only automatically close objects 
     * whose class implements the `java.lang.AutoCloseable` interface. 
     * This interface forces the class to override a single method: `close()`. When the try block finishes, the JVM 
     * simply loops through all resources defined in the parenthesis and invokes their `close()` method.
     */
    public void autoCloseable() {
        System.out.println("AutoCloseable: The interface contract required to utilize Try-With-Resources.");
    }

    /**
     * Q13: [Advanced] Detail the mechanics of Suppressed Exceptions.
     * 
     * DETAILED EXPLANATION:
     * A rare, complex scenario occurs in Try-With-Resources: 
     * 1. Your code inside the try block throws an Exception. The block crashes.
     * 2. The JVM steps in to automatically call `close()` on the resource.
     * 3. The `close()` method ALSO crashes and throws a completely different Exception!
     * 
     * Normally, the second exception would overwrite and hide the first one. Java solves this with Suppressed Exceptions. 
     * It throws the primary (try block) exception, but it attaches the secondary (close method) exception to it as a 
     * "suppressed" array. You can retrieve both by calling `primaryException.getSuppressed()`.
     */
    public void suppressedExceptions() {
        System.out.println("Suppressed Exceptions: Preserves secondary exceptions occurring during automated resource closures.");
    }

    /**
     * Q14: [Advanced] What is Exception Chaining?
     * 
     * DETAILED EXPLANATION:
     * Often, a low-level technical exception (like `SQLException` regarding a missing table column) occurs deep in 
     * a DAO class. You don't want to throw database errors all the way up to the UI. 
     * You catch the `SQLException`, and you throw a new, high-level business exception (like `UserRegistrationFailedException`). 
     * However, you pass the ORIGINAL `SQLException` into the constructor of the new exception. This creates a "Chain". 
     * The UI sees a clean business error, but the logging framework prints the entire chain (Caused by: SQLException), 
     * ensuring no debugging context is lost.
     */
    public void exceptionChaining() {
        System.out.println("Exception Chaining: Wrapping low-level technical errors inside high-level business errors.");
    }

    /**
     * Q15: [Easy] Dissect the NullPointerException (NPE).
     * 
     * DETAILED EXPLANATION:
     * The absolute most common error in Java. It is an Unchecked RuntimeException. 
     * It detonates when your code attempts to interact with an Object Reference variable that is currently 
     * pointing to `null` (nothing) instead of a physical object in the Heap. 
     * Common triggers: Calling a method on a null object, accessing a variable of a null object, or attempting 
     * to check `.length` on a null Array.
     */
    public void nullPointerException() {
        System.out.println("NPE: Attempting to invoke instance logic on an uninitialized (null) memory pointer.");
    }

    /**
     * Q16: [Easy] Dissect the ArrayIndexOutOfBoundsException.
     * 
     * DETAILED EXPLANATION:
     * An Unchecked RuntimeException. Arrays in Java have strict, immutable memory boundaries. If an array has a 
     * capacity of 10, valid indices are strictly 0 through 9. If you attempt to access index -1, or index 10, 
     * the JVM intercepts the request and throws this exception to prevent memory corruption or reading adjacent, 
     * unauthorized system memory.
     */
    public void arrayIndexOutOfBoundsException() {
        System.out.println("AIOOBE: Attempting to breach the strict index boundaries of an array container.");
    }

    /**
     * Q17: [Medium] Dissect the ClassCastException.
     * 
     * DETAILED EXPLANATION:
     * An Unchecked RuntimeException occurring during Downcasting. 
     * If you have a generic `Object` reference variable that is physically holding an `Integer` object in memory, 
     * and you forcefully try to cast it into a `String` (e.g., `String s = (String) myObj;`), the compiler might 
     * allow it, but the JVM at runtime will detect that the object shapes are totally incompatible and throw this exception.
     */
    public void classCastException() {
        System.out.println("CCE: Attempting to illegally morph an object into an incompatible subclass at runtime.");
    }

    /**
     * Q18: [Easy] Dissect the IllegalArgumentException.
     * 
     * DETAILED EXPLANATION:
     * An Unchecked RuntimeException used extensively in framework development. It is manually thrown by a developer 
     * at the very top of a method to validate incoming parameters. 
     * Example: If a method `setAge(int age)` is called with `-5`, the method immediately throws an IllegalArgumentException 
     * to stop processing, indicating that the caller provided garbage data.
     */
    public void illegalArgumentException() {
        System.out.println("IAE: Developer-thrown validation error indicating invalid method parameters.");
    }

    /**
     * Q19: [Medium] Dissect the IllegalStateException.
     * 
     * DETAILED EXPLANATION:
     * An Unchecked RuntimeException indicating that the overall "State" or lifecycle of the application is incorrect 
     * for the requested action. 
     * Example: Attempting to call `.start()` on a Thread object that has already been started and is currently running. 
     * The argument itself isn't bad, but the timing/state of the system makes the request illegal.
     */
    public void illegalStateException() {
        System.out.println("ISE: The system lifecycle is incompatible with the requested method execution.");
    }

    /**
     * Q20: [Advanced] Dissect the ConcurrentModificationException.
     * 
     * DETAILED EXPLANATION:
     * An Unchecked RuntimeException thrown primarily by Collections (like ArrayList or HashMap). 
     * It occurs when an active Iterator is currently looping through a collection, and the structural size of that 
     * collection is altered (an item is added or removed) by a completely different thread, or by a direct `list.remove()` 
     * call outside the Iterator's control. It protects against reading corrupted, shifting data streams.
     */
    public void concurrentModificationException() {
        System.out.println("CME: The underlying collection was mutated behind an active Iterator's back.");
    }

    /**
     * Q21: [Easy] What is the java.io.File Class?
     * 
     * DETAILED EXPLANATION:
     * The File class is widely misunderstood. It does NOT represent the actual contents or bytes of a file. 
     * It is simply an abstract, logical representation of a file or directory path on the operating system. 
     * You use it to check if a file physically exists (`.exists()`), determine if it's a folder (`.isDirectory()`), 
     * read its byte size, or delete it from the hard drive. You CANNOT use the File class to read text.
     */
    public void fileClass() {
        System.out.println("File: A metadata and pathing utility. Does not read or write file contents.");
    }

    /**
     * Q22: [Medium] What is a FileReader?
     * 
     * DETAILED EXPLANATION:
     * A convenience class tied to character-based streams. It connects to a physical file and pulls raw bytes off 
     * the hard drive, decoding them into human-readable characters. 
     * The massive flaw with FileReader is that it pulls data exactly ONE character at a time from the hard drive. 
     * Hitting the hard drive thousands of times for a large text file causes massive I/O bottlenecks and lag.
     */
    public void fileReader() {
        System.out.println("FileReader: Decodes bytes to characters, but incredibly slow due to unbuffered 1-by-1 reading.");
    }

    /**
     * Q23: [Medium] What is a FileWriter?
     * 
     * DETAILED EXPLANATION:
     * The counterpart to FileReader. It takes Java strings or characters and writes them directly onto the hard drive. 
     * Like its counterpart, it suffers from severe unbuffered performance issues if writing massive amounts of data directly.
     */
    public void fileWriter() {
        System.out.println("FileWriter: Writes characters to the disk, suffering from unbuffered performance issues.");
    }

    /**
     * Q24: [Medium] Why is BufferedReader critical for performance?
     * 
     * DETAILED EXPLANATION:
     * You take a slow `FileReader` and "wrap" it inside a `BufferedReader` (Decorator Pattern). 
     * Instead of hitting the hard drive for every single letter, the BufferedReader hits the hard drive once, scoops 
     * up a massive 8 Kilobyte chunk of text into a fast memory array (a buffer), and lets your Java code read from 
     * RAM instantly. It also provides the vital `.readLine()` method, allowing you to parse text files cleanly line by line.
     */
    public void bufferedReader() {
        System.out.println("BufferedReader: Slashes hard-drive latency by scooping data into bulk RAM memory buffers.");
    }

    /**
     * Q25: [Medium] Why is BufferedWriter critical for performance?
     * 
     * DETAILED EXPLANATION:
     * Wraps around a FileWriter. Instead of writing letters to the hard drive one by one (causing disk spin), it 
     * holds your text in a fast memory array. Only when the array gets completely full does it execute a single, 
     * massive "flush" operation to write everything to the disk at once, vastly extending hard drive lifespan and speed.
     */
    public void bufferedWriter() {
        System.out.println("BufferedWriter: Accumulates output in RAM before executing massive bulk disk writes.");
    }

    /**
     * Q26: [Medium] Explain InputStream vs Reader.
     * 
     * DETAILED EXPLANATION:
     * `Reader` (and FileReader) are strictly for Human-Readable TEXT (characters, UTF-8). 
     * `InputStream` (and FileInputStream) is the raw foundation. It reads pure, 8-bit RAW BYTES. 
     * If you are processing a JPEG image, an MP3 audio file, a compiled executable, or a network socket payload, 
     * you MUST use an InputStream. A Reader would attempt to decode the image bytes into text, completely destroying the file.
     */
    public void inputStream() {
        System.out.println("InputStream: The raw foundation handling pure 8-bit bytes (Images, Audio, Network traffic).");
    }

    /**
     * Q27: [Medium] Explain OutputStream vs Writer.
     * 
     * DETAILED EXPLANATION:
     * Exactly like the input side. `Writer` formats and outputs human-readable characters. 
     * `OutputStream` transmits raw binary byte arrays. Used for generating zip files, sending encrypted network 
     * payloads, or writing image processing outputs.
     */
    public void outputStream() {
        System.out.println("OutputStream: Transmits raw, unformatted binary byte payloads to disks or networks.");
    }

    /**
     * Q28: [Advanced] Deeply explain Object Serialization.
     * 
     * DETAILED EXPLANATION:
     * Serialization is a magical JVM process. It takes a fully instantiated, complex, multi-layered Java Object 
     * residing in Heap memory, and flattens its entire state (all variables and nested objects) into a linear 
     * sequence of raw bytes. 
     * This byte array can then be saved physically to a `.txt` file, inserted into a Database Blob, or fired 
     * across the internet to a totally different server. 
     * Requirement: The class MUST implement the `java.io.Serializable` marker interface, otherwise an exception is thrown.
     */
    public void serialization() {
        System.out.println("Serialization: Freezes a 3D memory object into a 1D byte sequence for transmission or storage.");
    }

    /**
     * Q29: [Advanced] Deeply explain Object Deserialization.
     * 
     * DETAILED EXPLANATION:
     * The exact reverse of Serialization. A Java application receives a stream of bytes (from a file or a network socket). 
     * The `ObjectInputStream` reads these bytes and algorithmically re-inflates and reconstructs the exact original 
     * Java Object back into the Heap memory, complete with all its previous variables and state intact. 
     * Warning: If the Java Class file definition has changed since the object was serialized, a `InvalidClassException` occurs.
     */
    public void deserialization() {
        System.out.println("Deserialization: Thaws a byte sequence back into a fully functioning Java Object in memory.");
    }

    /**
     * Q30: [Medium] What is the 'transient' Keyword and when is it used?
     * 
     * DETAILED EXPLANATION:
     * When you serialize an Object, Java captures every single instance variable. 
     * If an object contains a `password`, a `socialSecurityNumber`, or a generic temporary counter that doesn't 
     * need to be saved to the database, you mark that specific variable with the `transient` keyword. 
     * The Serialization engine sees `transient` and completely ignores that variable. When the object is Deserialized 
     * later, that specific variable will simply be injected with its default value (like `null` or `0`).
     */
    public void transientKeyword() {
        System.out.println("Transient: Acts as an invisibility cloak, hiding sensitive variables from the Serialization engine.");
    }
}