package interviewQuestions;

import java.util.*;

/**
 * ============================================================================
 * INTERVIEW QUESTIONS PART 10: Modern Java & Test Automation Patterns
 * ============================================================================
 * This file contains 30 highly detailed Java interview questions.
 * Each question provides a deep-dive English explanation covering the 'What', 
 * 'Why', and 'How', along with practical Java code snippets.
 * ============================================================================
 */
public class Part10_ModernJavaAndPatterns {

    public static void main(String[] args) {
        System.out.println("Running Part 10: Modern Java & Automation Patterns...");
    }

    /**
     * Q1: [Medium] Detail Java 9 Factory Methods for Collections.
     * 
     * DETAILED EXPLANATION:
     * Pre-Java 9, instantiating a pre-populated ArrayList took multiple lines of `add()` calls, or clunky arrays.asList. 
     * Java 9 introduced `List.of()`, `Set.of()`, and `Map.of()`. 
     * These generate collections incredibly cleanly. CRITICAL CAVEAT: The collections generated by these factory 
     * methods are strictly Immutable. Any attempt to add, remove, or sort elements will throw an UnsupportedOperationException. 
     * Furthermore, they absolutely reject `null` elements.
     */
    public void java9FactoryMethods() {
        System.out.println("List.of(): Clean syntax generating strictly Immutable, null-rejecting collections.");
    }

    /**
     * Q2: [Advanced] What is the primary architectural goal of Java 9 Modules (Project Jigsaw)?
     * 
     * DETAILED EXPLANATION:
     * For 20 years, the JDK was a massive, bloated monolith. Project Jigsaw broke the JDK into tiny, manageable 
     * modules. 
     * For application developers, the Module system introduces Strong Encapsulation above the 'package' level. 
     * Using a `module-info.java` file, you can explicitly declare which of your internal packages are `exported` 
     * (visible to other teams) and which are completely hidden. It also drastically reduces memory overhead, as you 
     * can deploy an application with a custom, stripped-down JVM containing only the specific modules you need.
     */
    public void java9Modules() {
        System.out.println("Modules: Strong architectural encapsulation and dynamic JVM minimization.");
    }

    /**
     * Q3: [Easy] Detail the Java 10 'var' Keyword. What are its strict limits?
     * 
     * DETAILED EXPLANATION:
     * `var` enables Local Variable Type Inference. Instead of writing `HashMap<String, Integer> map = new HashMap<>()`, 
     * you write `var map = new HashMap<String, Integer>()`. The Java compiler looks at the right side of the equals 
     * sign and permanently locks in the type. 
     * LIMITS: It ONLY works for variables local to a method. You CANNOT use `var` for class-level instance variables, 
     * method parameters, or method return types. You also cannot declare `var x;` without instantly initializing it, 
     * because the compiler wouldn't know what type to guess.
     */
    public void java10VarKeyword() {
        System.out.println("var: Boilerplate reduction via compiler type-inference. Strictly for Local Variables.");
    }

    /**
     * Q4: [Medium] Highlight critical Java 11 String Enhancements.
     * 
     * DETAILED EXPLANATION:
     * Java 11 introduced immensely useful string utilities.
     * - `isBlank()`: Superior to `isEmpty()`. Returns true if a string is completely empty OR if it only contains 
     *   invisible whitespace (spaces, tabs, newlines).
     * - `strip()`: Superior to the old `trim()`. It removes leading and trailing whitespaces, but it leverages modern 
     *   Unicode definitions, making it much more robust across different language encodings.
     * - `repeat(N)`: Instantly duplicates a string N times without loops.
     * - `lines()`: Returns a `Stream<String>` by cleanly slicing a massive multiline text block at every carriage return.
     */
    public void java11StringMethods() {
        System.out.println("Java 11 Strings: Robust Unicode-aware whitespace handling and Stream integration.");
    }

    /**
     * Q5: [Medium] Why did Java 11 introduce a Native HTTP Client?
     * 
     * DETAILED EXPLANATION:
     * The legacy `HttpURLConnection` class was written in the 1990s. It was clunky, hard to read, only supported 
     * blocking requests, and required massive amounts of boilerplate code. 
     * The `java.net.http.HttpClient` API is a modern, fluent, builder-pattern based interface. It natively supports 
     * both Synchronous and completely Asynchronous (non-blocking) requests via `CompletableFuture`. It fully supports 
     * HTTP/2 protocols and WebSockets right out of the box, eliminating the need for bulky 3rd party libraries 
     * like Apache HttpClient in many microservices.
     */
    public void java11HttpClient() {
        System.out.println("HTTP Client: Modern, asynchronous, fluent-API natively supporting HTTP/2.");
    }

    /**
     * Q6: [Medium] Detail the architectural improvements of Java 14 Switch Expressions.
     * 
     * DETAILED EXPLANATION:
     * The legacy `switch` statement was prone to catastrophic "Fall-Through" bugs if a developer forgot a `break;` command. 
     * The Java 14 Switch Expression revolutionizes this. 
     * 1. It utilizes Lambda arrow syntax `->`. It evaluates the condition, executes the block on the right, and 
     *    automatically terminates. No `break` required.
     * 2. It allows comma-separated multi-matching (`case 1, 2, 3 ->`).
     * 3. It can be used as an Expression, meaning the entire switch block evaluates to a value that can be instantly 
     *    assigned to a variable (`String result = switch(val) {...};`).
     */
    public void java14SwitchExpressions() {
        System.out.println("Switch Expressions: Eradicates fall-through bugs and enables direct variable assignment.");
    }

    /**
     * Q7: [Easy] What is the impact of Java 14 Helpful NullPointerExceptions?
     * 
     * DETAILED EXPLANATION:
     * Historically, if `person.getAddress().getCity().length()` threw a NullPointerException, the log only provided 
     * the line number. Developers had to guess if 'person', 'address', or 'city' was the culprit. 
     * Java 14 updated the JVM's byte-code analyzer. The stack trace now explicitly states: "Cannot invoke 'getCity()' 
     * because the return value of 'getAddress()' is null." This slashes debugging time drastically.
     */
    public void java14NullPointerDetails() {
        System.out.println("Helpful NPEs: JVM precisely identifies the exact object causing the crash.");
    }

    /**
     * Q8: [Easy] How do Java 15 Text Blocks improve code maintainability?
     * 
     * DETAILED EXPLANATION:
     * Text Blocks (denoted by opening `"""` and a newline) allow developers to paste massive chunks of SQL queries, 
     * HTML, or JSON directly into Java code. 
     * Prior to this, you had to manually concatenate strings with `+` and escape every single quote mark `\"`. 
     * Text Blocks respect actual carriage returns and indentation natively, making complex multi-line strings 
     * completely readable without escape-character clutter.
     */
    public void java15TextBlocks() {
        System.out.println("Text Blocks: Multi-line string literals eradicating concatenation and escape-character bloat.");
    }

    /**
     * Q9: [Medium] Deeply explain Java 16 Records. What problem do they solve?
     * 
     * DETAILED EXPLANATION:
     * To create a simple Data Transfer Object (DTO) in Java historically required 50 lines of code: private variables, 
     * a massive constructor, getters, and manually overriding `equals`, `hashCode`, and `toString`. 
     * A `record` is a restricted form of a Class. In one single line (`record Point(int x, int y) {}`), the Java 
     * compiler automatically generates ALL of that boilerplate code. 
     * Crucially: Records are strictly Immutable. They cannot be extended, and their variables cannot be mutated once set.
     */
    public void java16Records() {
        System.out.println("Records: Instantaneous generation of Immutable Data Carriers with zero boilerplate.");
    }

    /**
     * Q10: [Medium] How does Java 16 Pattern Matching for instanceof clean up code?
     * 
     * DETAILED EXPLANATION:
     * The old pattern was tedious: `if (obj instanceof String) { String s = (String) obj; s.toLowerCase(); }`. 
     * You checked the type, and then you were forced to immediately write a redundant manual cast. 
     * Pattern matching fuses these steps: `if (obj instanceof String s) { s.toLowerCase(); }`. 
     * The JVM checks the type, and if true, automatically casts it and binds it to the newly scoped variable 's' 
     * right inside the condition statement.
     */
    public void java16PatternMatching() {
        System.out.println("Pattern Matching: Eliminates redundant manual casting after conditional type checks.");
    }

    /**
     * Q11: [Advanced] Explain the security value of Java 17 Sealed Classes.
     * 
     * DETAILED EXPLANATION:
     * Before Java 17, a class was either `final` (nobody can inherit it) or completely open (anyone can inherit it). 
     * Sealed Classes provide granular control. By declaring `public sealed class Shape permits Circle, Square`, you 
     * explicitly tell the compiler that ONLY Circle and Square are legally allowed to extend Shape. 
     * If a malicious hacker tries to write `class EvilShape extends Shape`, the compiler instantly violently rejects 
     * it. It is critical for defining strict business domains where unknown subclassing is dangerous.
     */
    public void java17SealedClasses() {
        System.out.println("Sealed Classes: Strict compiler-enforced whitelists restricting inheritance hierarchies.");
    }

    /**
     * Q12: [Advanced] Why are Java 21 Virtual Threads considered a paradigm shift?
     * 
     * DETAILED EXPLANATION:
     * Traditional "Platform Threads" map 1-to-1 with Operating System threads. They are incredibly heavy, consuming 
     * 1MB+ of RAM each. A server crashes if it tries to spawn 10,000 threads. 
     * Virtual Threads (Project Loom) break this mapping. They are managed entirely by the JVM, not the OS. They are 
     * so lightweight that a standard laptop can effortlessly spawn 1,000,000 Virtual Threads simultaneously. 
     * This completely eradicates the need for complex reactive, non-blocking frameworks (like WebFlux), allowing 
     * developers to write standard synchronous, blocking code that scales limitlessly.
     */
    public void java21VirtualThreads() {
        System.out.println("Virtual Threads: Hyper-lightweight JVM threads enabling millions of parallel blocking tasks.");
    }

    /**
     * Q13: [Medium] What is Java 21 Pattern Matching for Switch?
     * 
     * DETAILED EXPLANATION:
     * It allows Switch statements to become powerful data extractors. Instead of just checking if a variable equals 
     * an integer or a string, it checks the actual Class Type. 
     * `switch(obj) { case Integer i -> print(i); case String s -> print(s.length()); }`. 
     * Combined with Sealed Classes, the compiler can guarantee Exhaustiveness—ensuring you have written a `case` for 
     * every possible permitted subclass, completely eliminating `default` case bugs.
     */
    public void java21PatternMatchingSwitch() {
        System.out.println("Pattern Matching Switch: Type-based routing enabling exhaustive domain-specific logic.");
    }

    /**
     * Q14: [Medium] Explain Java 21 Sequenced Collections.
     * 
     * DETAILED EXPLANATION:
     * Historically, getting the last element of a LinkedHashSet was confusing and lacked unified interfaces. 
     * Java 21 introduced `SequencedCollection`, `SequencedSet`, and `SequencedMap` interfaces. 
     * These interfaces define standardized methods like `getFirst()`, `getLast()`, `addFirst()`, `addLast()`, and 
     * `reversed()` across ALL collection implementations that possess a defined encounter order. It brings massive 
     * uniformity to the Collections framework.
     */
    public void java21SequencedCollections() {
        System.out.println("Sequenced Collections: Unified interfaces standardizing interactions with ordered data.");
    }

    /**
     * Q15: [Advanced] Explain the core mechanic of Garbage Collection.
     * 
     * DETAILED EXPLANATION:
     * Garbage Collection (GC) automates memory management. The JVM periodically runs a "Mark and Sweep" algorithm. 
     * 1. Mark: The GC scans from "GC Roots" (active threads, static variables, local variables) and traces every 
     *    single object reference tree. Any object it touches is marked as "Alive".
     * 2. Sweep: The GC scans the Heap. Any object that was NOT marked (meaning no active variable points to it 
     *    anymore) is flagged as garbage. Its memory is wiped and reclaimed. 
     * This saves Java developers from manual memory leaks prevalent in C/C++.
     */
    public void garbageCollectionBasics() {
        System.out.println("GC: Traces active memory paths and systematically eradicates orphaned, unreachable objects.");
    }

    /**
     * Q16: [Medium] Describe the Page Object Model (POM) in Test Automation.
     * 
     * DETAILED EXPLANATION:
     * POM is the absolute gold standard design pattern for UI automation. It completely separates test assertions 
     * from UI interaction logic. 
     * For every physical webpage (e.g., 'LoginPage'), you create a corresponding Java Class (`LoginPage.java`). 
     * All WebElements (Buttons, TextBoxes) and actions (`login()`) are encapsulated in this class. The Test class 
     * simply calls `loginPage.login()`. If the UI's HTML structure changes, you only update the POM class, and all 
     * 500 tests relying on it are instantly fixed.
     */
    public void pageObjectModel() {
        System.out.println("POM: Architectural separation of Page UI Definitions from Test Assertion scripts.");
    }

    /**
     * Q17: [Medium] What is Data Driven Testing (DDT)?
     * 
     * DETAILED EXPLANATION:
     * A framework philosophy where the test logic and the test data are heavily decoupled. 
     * Instead of hardcoding "Username1" and "Password2" into the Java method, the test reads data from an external 
     * source (JSON, Excel, Database). Using tools like TestNG `@DataProvider`, a single test method can be executed 
     * 100 consecutive times, pulling a new row of data for every iteration. This achieves maximum test coverage 
     * with minimal code.
     */
    public void dataDrivenTesting() {
        System.out.println("DDT: Iterative execution of a single script powered by external data matrices.");
    }

    /**
     * Q18: [Advanced] Differentiate Keyword Driven from Data Driven Testing.
     * 
     * DETAILED EXPLANATION:
     * In DDT, data is external. In Keyword Driven Testing (KDT), the actual ACTIONS are external. 
     * An Excel file might have a row: "Click_Button | Login_Btn". The Java framework reads the action "Click_Button" 
     * from the Excel file, uses complex Reflection or Switch logic to find the Java method named "Click_Button", 
     * and executes it. This allows Manual Testers who don't know Java to write automated test scripts entirely in Excel.
     */
    public void keywordDrivenTesting() {
        System.out.println("KDT: Externalizing behavioral execution logic to empower non-programmers.");
    }

    /**
     * Q19: [Medium] Explain Behavior Driven Development (BDD).
     * 
     * DETAILED EXPLANATION:
     * BDD bridges the gap between Business Analysts, Manual Testers, and SDETs. 
     * Test scenarios are written in plain English using the Gherkin syntax ("Given I am on the login page, When I enter 
     * valid credentials, Then I should see the dashboard"). 
     * Frameworks like Cucumber parse these text files and map each English sentence directly to an underlying Java 
     * method via Regex annotations (`@Given(\"^I am on the login page$\")`). It ensures test output perfectly aligns 
     * with Agile business requirements.
     */
    public void bdd() {
        System.out.println("BDD: Aligning technical automation execution with human-readable business requirements.");
    }

    /**
     * Q20: [Medium] What is a Fluent Interface Design Pattern?
     * 
     * DETAILED EXPLANATION:
     * An API design pattern heavily reliant on "Method Chaining" to create highly readable, DSL-like syntax. 
     * Instead of a method completing its work and returning `void`, it returns `this` (the current object instance). 
     * This allows subsequent methods to be called immediately in a single chain. 
     * Example: `loginPage.enterUsername(\"Bob\").enterPassword(\"123\").clickSubmit();` It vastly improves test readability.
     */
    public void fluentInterface() {
        System.out.println("Fluent Interface: Returns 'this' to chain method calls into highly readable sentences.");
    }

    /**
     * Q21: [Medium] Hard Assertions vs Soft Assertions?
     * 
     * DETAILED EXPLANATION:
     * A Hard Assertion (`Assert.assertEquals`) behaves ruthlessly: the millisecond it fails, it throws an AssertionException 
     * and permanently aborts the rest of the test script. 
     * A Soft Assertion (`SoftAssert soft = new SoftAssert()`) is forgiving. If a verification fails, it logs the failure 
     * internally, but allows the test script to continue executing the remaining lines. You MUST call `soft.assertAll()` 
     * at the absolute end of the test. It will then dump all collected failures. Useful for checking multiple non-critical 
     * UI elements in a single flow.
     */
    public void softAssertions() {
        System.out.println("Soft Assertions: Accumulates validation failures without instantly aborting test execution.");
    }

    /**
     * Q22: [Advanced] Why is WebDriver Thread Safety critical in parallel execution?
     * 
     * DETAILED EXPLANATION:
     * When TestNG is configured to run 5 tests in parallel (`parallel=\"methods\" thread-count=\"5\"`), it spawns 5 active threads. 
     * If you instantiate a `public static WebDriver driver;`, Thread 1 will launch Chrome. A millisecond later, Thread 2 
     * will overwrite that variable with Firefox. Thread 1's test will suddenly crash because its browser pointer vanished. 
     * By wrapping the driver in `ThreadLocal<WebDriver>`, the JVM creates a totally isolated variable silo for each thread. 
     * Thread 1 gets its driver, Thread 2 gets its driver, and they remain perfectly separated.
     */
    public void webDriverThreadSafety() {
        System.out.println("Thread Safety: Mitigated via ThreadLocal to isolate browser instances across parallel executions.");
    }

    /**
     * Q23: [Medium] Describe mechanisms for Parallel Test Execution.
     * 
     * DETAILED EXPLANATION:
     * Running 1,000 UI tests sequentially takes hours. Parallel execution executes them simultaneously, cutting time drastically. 
     * In TestNG, this is achieved via the `testng.xml` suite file. You specify `parallel=\"methods\"` (or classes/tests) and 
     * define a `thread-count=\"10\"`. TestNG then automatically spawns a ThreadPoolExecutor and disperses the test methods 
     * across the active threads. 
     * Caveat: The automation framework MUST be meticulously designed to be Thread-Safe (no shared static state).
     */
    public void parallelTestExecution() {
        System.out.println("Parallel Execution: Distributing test suites across Thread Pools via TestNG configuration.");
    }

    /**
     * Q24: [Medium] How do you systematically Handle Flaky Tests?
     * 
     * DETAILED EXPLANATION:
     * A flaky test passes locally but randomly fails in CI/CD. Primary causes are asynchronous UI rendering, network latency, 
     * or stale data states. 
     * Solutions: 
     * 1. Eradicate `Thread.sleep()` completely. Use Explicit/Fluent Waits that actively poll the DOM for specific conditions. 
     * 2. Ensure rigorous Test Data Isolation (tests generate and tear down their own specific data, not relying on global DB state). 
     * 3. Implement Automatic Retry logic for genuine network blips.
     */
    public void handlingFlakyTests() {
        System.out.println("Flaky Tests: Stabilized through Explicit Waits, Data Isolation, and Retry Analyzers.");
    }

    /**
     * Q25: [Medium] What is the implementation logic of a Retry Analyzer?
     * 
     * DETAILED EXPLANATION:
     * TestNG provides the `IRetryAnalyzer` interface. You override the `retry(ITestResult result)` method. 
     * You maintain an internal integer counter. When a test crashes, TestNG calls this method. If you return `true`, 
     * TestNG suppresses the failure and executes the exact same test method again. If it passes on the 2nd try, the pipeline 
     * stays green. If the counter maxes out (e.g., 3 retries), you return `false`, and TestNG permanently fails the test.
     */
    public void retryAnalyzer() {
        System.out.println("Retry Analyzer: Intercepts failures and conditionally commands TestNG to re-execute the method.");
    }

    /**
     * Q26: [Medium] Detail standard API Response Validation techniques.
     * 
     * DETAILED EXPLANATION:
     * UI testing is slow. API testing is instantaneous. 
     * Core validations include: 
     * 1. Status Code Validation (Asserting 200 OK vs 404/500). 
     * 2. Schema Validation (Ensuring the JSON structure precisely matches the API contract using JSON Schema tools). 
     * 3. Payload Validation (Using JSONPath in tools like RestAssured to verify exact values, e.g., `body(\"user.id\", equalTo(5))`). 
     * 4. Performance Validation (Asserting response time < 500ms).
     */
    public void apiResponseValidation() {
        System.out.println("API Validation: Status Codes, Schema Contracts, JSONPath exact matching, and Latency checks.");
    }

    /**
     * Q27: [Medium] How is JSON Parsing executed in Java?
     * 
     * DETAILED EXPLANATION:
     * Java does not natively understand JSON. You rely on heavy-duty libraries like Jackson or Gson. 
     * - Serialization: Converting a Java POJO (like `User`) into a JSON String to send in an HTTP POST body. (e.g., `objectMapper.writeValueAsString(user)`).
     * - Deserialization: Converting an incoming HTTP JSON response String back into a functioning Java Object for easy assertion. (e.g., `objectMapper.readValue(jsonString, User.class)`).
     */
    public void jsonParsingWithJava() {
        System.out.println("JSON Parsing: Serialization/Deserialization mapping JSON strings to Java POJOs via Jackson/Gson.");
    }

    /**
     * Q28: [Medium] How do you handle Reading Excel files in Java?
     * 
     * DETAILED EXPLANATION:
     * Java has no native Excel support. SDETs universally rely on the Apache POI library. 
     * Logic flow: 
     * 1. Open a `FileInputStream` to the `.xlsx` file. 
     * 2. Wrap it in an `XSSFWorkbook` object. 
     * 3. Access a specific `XSSFSheet`. 
     * 4. Iterate through `XSSFRow` objects. 
     * 5. Extract data from `XSSFCell` objects using `getStringCellValue()` or `getNumericCellValue()`. 
     * Often used to load massive 2D Arrays into TestNG DataProviders.
     */
    public void readingExcelInJava() {
        System.out.println("Excel Reading: Powered by Apache POI XSSF API to extract nested Row/Cell structures.");
    }

    /**
     * Q29: [Medium] Describe the core components of Database Connection (JDBC).
     * 
     * DETAILED EXPLANATION:
     * Java Database Connectivity is the native API for relational databases. 
     * 1. Register the Driver (e.g., MySQL Driver). 
     * 2. Establish a `Connection` via `DriverManager.getConnection(url, user, pass)`. 
     * 3. Create a `Statement` or a `PreparedStatement` (which is compiled and protects against SQL Injection). 
     * 4. Execute the query, yielding a `ResultSet`. 
     * 5. Iterate through the `ResultSet` pulling specific column data. 
     * 6. CRITICALLY: Close the connection (or use Try-With-Resources) to prevent catastrophic DB lockups.
     */
    public void databaseConnection() {
        System.out.println("JDBC: Connection -> PreparedStatement -> ResultSet execution flow.");
    }

    /**
     * Q30: [Easy] Detail critical TestNG / JUnit Annotations.
     * 
     * DETAILED EXPLANATION:
     * Annotations are metadata instructions dictating the execution pipeline to the testing framework.
     * - `@Test`: Marks the method as a standalone executable test case.
     * - `@BeforeMethod`: Setup logic (like launching browser) executed before EVERY single `@Test`.
     * - `@AfterMethod`: Teardown logic (like closing browser) executed after EVERY single `@Test`.
     * - `@BeforeClass`: Heavy setup logic executed ONCE before any test in the class begins.
     * - `@DataProvider`: Defines a method that returns a 2D Array matrix, feeding iterative data directly into a `@Test`.
     */
    public void testAnnotations() {
        System.out.println("Annotations: Architectural metadata driving test lifecycle hooks and configuration.");
    }
}